---
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  url_launcher: ^6.2.4
description: A new Flutter project.
dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
environment:
  sdk: '>=3.0.5 <4.0.0'
flutter:
  uses-material-design: true
name: listening_app
publish_to: none
version: 1.0.0+1